# Create a function, that accepts an arbitrary number
# of arrays and returns a single array generated by
# alternately appending elements from the passed in
# arguments. If one of them is shorter than the others,
# the result should be padded with empty elements.


def interleave(*args):
    result = []
    max_len = max(len(lst) for lst in args)

    for i in range(max_len):
        for lst in args:
            if i < len(lst):
                result.append(lst[i])
            else:
                result.append(None)
    return result


print(interleave([1, 2, 3], [4, 5]))
